import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

public class anggota extends javax.swing.JFrame {
    Statement st;
    Connection koneksi;
    ResultSet Res;
    PreparedStatement stat;
    
    public anggota() {
        initComponents();
        setLocationRelativeTo(null);
        koneksi();
        tampilkan();
    }
    
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    
    private void tampilkan() {
        DefaultTableModel grid = new  DefaultTableModel();
        grid.addColumn("Stambuk");
        grid.addColumn("Nama Anggota");
        grid.addColumn("Tanggal Lahir");
        grid.addColumn("Jenis Kelamin");
        grid.addColumn("Alamat");
        grid.addColumn("Kelas");
        tabelanggota.setModel(grid);
        try {
            st =  koneksi.createStatement();
            Res = st.executeQuery("Select * from anggota");
            while (Res.next()) {
                grid.addRow(new Object[]{
                    Res.getString("stambuk"),
                    Res.getString("namaAnggota"),
                    Res.getString("tanggalLahir"),
                    Res.getString("jenisKelamin"),
                    Res.getString("alamat"),
                    Res.getString("kelas"),
                });
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil "+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelanggota = new javax.swing.JTable();
        txtstambuk = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtttl = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtkelas = new javax.swing.JTextField();
        cbtjnskelamin = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        btambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA ANGGOTA");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("STAMBUK");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("NAMA");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("ALAMAT");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("KELAS");

        tabelanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelanggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelanggota);

        txtstambuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtnama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtttl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtalamat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtkelas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbtjnskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        bsimpan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bedit.setText("EDIT");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        txtcari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bcari.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bcari.setText("CARI");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        btambah.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addGap(56, 56, 56)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                                .addComponent(txtstambuk)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(25, 25, 25)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtttl, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cbtjnskelamin, javax.swing.GroupLayout.Alignment.TRAILING, 0, 146, Short.MAX_VALUE)
                                                .addComponent(txtalamat)
                                                .addComponent(txtkelas))))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bsimpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(bedit))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(bhapus)
                                                .addGap(18, 18, 18)
                                                .addComponent(bkeluar)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btambah)))))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcari)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(txtstambuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsimpan)
                    .addComponent(bedit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbtjnskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bhapus)
                    .addComponent(bkeluar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btambah)
                        .addGap(10, 10, 10)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelanggotaMouseClicked
        int a = tabelanggota.getSelectedRow();
        if (a == -1){
            return;
        }
        String stambuk = (String) tabelanggota.getValueAt(a, 0);
        txtstambuk.setText(stambuk);
        String nama = (String) tabelanggota.getValueAt(a, 1);
        txtnama.setText(nama);
        String ttl = (String) tabelanggota.getValueAt(a, 2);
        txtttl.setText(ttl);
        String jeniskelamin = (String) tabelanggota.getValueAt(a, 3);
        cbtjnskelamin.setSelectedItem(jeniskelamin);
        String alamat = (String) tabelanggota.getValueAt(a, 4);
        txtalamat.setText(alamat);
        String kelas = (String) tabelanggota.getValueAt(a, 5);
        txtkelas.setText(kelas);
    }//GEN-LAST:event_tabelanggotaMouseClicked

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String stambuk = txtstambuk.getText();
        String nama = txtnama.getText();
        String ttl = txtttl.getText();
        String alamat = txtalamat.getText();
        String kelas = txtkelas.getText();
        String jeniskelamin = (String) cbtjnskelamin.getSelectedItem();
        try {
            st = koneksi.createStatement();
            st.executeUpdate("insert into anggota VALUES ('"+ stambuk +"','"
                    + nama +"','"
                    + ttl +"','"
                    + jeniskelamin +"','"
                    + alamat +"','"
                    + kelas +"');");
            tampilkan();
            JOptionPane.showMessageDialog(null, "Data Behasil Disimpan");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        String stambuk = txtstambuk.getText();
        String nama = txtnama.getText();
        String ttl = txtttl.getText();
        String alamat = txtalamat.getText();
        String kelas = txtkelas.getText();
        String jeniskelamin = (String) cbtjnskelamin.getSelectedItem();
        try {
            st = koneksi.createStatement();
                st.executeUpdate("update anggota SET stambuk='"+stambuk+"',"
                        +"namaAnggota='"+nama+"',"
                        +"tanggalLahir='"+ttl+"',"
                        +"jenisKelamin='"+jeniskelamin+"',"
                        +"alamat='"+alamat+"',"
                        +"kelas='"+kelas+"'" 
                        + "WHERE stambuk='"+stambuk+"' OR namaAnggota='"+nama+"'");
            tampilkan();
            JOptionPane.showMessageDialog(null, "Teredit");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Teredit\n"+e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String stambuk = txtstambuk.getText();
        String nama = txtnama.getText();
        String ttl = txtttl.getText();
        String alamat = txtalamat.getText();
        String kelas = txtkelas.getText();
        String jeniskelamin = (String) cbtjnskelamin.getSelectedItem();
        try {
            st = koneksi.createStatement();
            st.executeUpdate("delete from anggota where stambuk='"+stambuk+"' OR namaAnggota='"+nama+"';");
            tampilkan();
            JOptionPane.showMessageDialog(null, "Terhapus");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Terhapus\n"+e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        try {
            st = koneksi.createStatement();
            Res = st.executeQuery("Select*from anggota where "+"stambuk like '%"+txtcari.getText()+"%' OR "+"namaAnggota like '%"+txtcari.getText()+"%'");
            DefaultTableModel grid = new  DefaultTableModel();
            grid.addColumn("Stambuk");
            grid.addColumn("Nama Anggota");
            grid.addColumn("Tanggal Lahir");
            grid.addColumn("Jenis Kelamin");
            grid.addColumn("Alamat");
            grid.addColumn("Kelas");

            tabelanggota.setModel(grid);
            while (Res.next()){
                grid.addRow(new Object[] {
                    Res.getString("stambuk"),
                    Res.getString("namaAnggota"),
                    Res.getString("tanggalLahir"),
                    Res.getString("jenisKelamin"),
                    Res.getString("alamat"),
                    Res.getString("kelas"),
                });
                tabelanggota.setModel(grid);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        txtstambuk.setText("");
        txtnama.setText("");
        txtttl.setText("");
        cbtjnskelamin.setSelectedItem("Laki-Laki");
        txtalamat.setText("");
        txtkelas.setText("");
        txtstambuk.requestFocus();
    }//GEN-LAST:event_btambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JComboBox<String> cbtjnskelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelanggota;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtstambuk;
    private javax.swing.JTextField txtttl;
    // End of variables declaration//GEN-END:variables
}
