import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.sql.SQLException;


public class Buku extends javax.swing.JFrame {
    Statement st;
    Connection koneksi;
    ResultSet Res;
 
    public Buku() {
        initComponents();
        koneksiBuku();
        Tampilbuku();
    }
    
    private void koneksiBuku(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    
    private void Tampilbuku(){
        DefaultTableModel tbl = new  DefaultTableModel();
        tbl.addColumn("Kode Buku");
        tbl.addColumn("Judul Buku");
        tbl.addColumn("Pengarang");
        tbl.addColumn("Penerbit");
        tbl.addColumn("Tahun Terbit");
        tbl.addColumn("Harga Buku");
        tabel1.setModel(tbl);
        try {
            st =  koneksi.createStatement();
            ResultSet res = st.executeQuery("Select * from buku");
            while (res.next()) {
                tbl.addRow(new Object[]{
                    res.getString("kodeBuku"),
                    res.getString("judulBuku"),
                    res.getString("pengarang"),
                    res.getString("penerbit"),
                    res.getString("tahunTerbit"),
                    res.getString("hargaBuku"),
                });
                tabel1.setModel(tbl);
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Tampil "+e);
        }
    }
    
    private void kosongkan (){
        txtkodebuku.setText("");
        txtjdlbuku.setText("");
        txtpengarang.setText("");
        txtthnterbit.setText("");
        txtpenerbit.setText("");
        txtkodebuku.requestFocus();
        txtharga.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        databuku = new javax.swing.JLabel();
        kodebuku = new javax.swing.JLabel();
        jdlbuku = new javax.swing.JLabel();
        pengarang = new javax.swing.JLabel();
        thnterbit = new javax.swing.JLabel();
        penerbit = new javax.swing.JLabel();
        txtkodebuku = new javax.swing.JTextField();
        txtjdlbuku = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        bsimpan = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        hargabuku = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        btambah = new javax.swing.JButton();
        txtthnterbit = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.gray);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        databuku.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        databuku.setText("Data Buku");

        kodebuku.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        kodebuku.setText("KODE BUKU");

        jdlbuku.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jdlbuku.setText("JUDUL BUKU");

        pengarang.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        pengarang.setText("PENGARANG");

        thnterbit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        thnterbit.setText("TAHUN TERBIT");

        penerbit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        penerbit.setText("PENERBIT");

        txtkodebuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodebukuActionPerformed(evt);
            }
        });
        txtkodebuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkodebukuKeyPressed(evt);
            }
        });

        txtjdlbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjdlbukuActionPerformed(evt);
            }
        });

        txtpengarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpengarangActionPerformed(evt);
            }
        });

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel1);

        bsimpan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bedit.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bedit.setText("Edit");
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        hargabuku.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        hargabuku.setText("HARGA BUKU");

        txtharga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btambah.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btambah.setText("+");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });

        txtthnterbit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bedit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bhapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bkeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btambah))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pengarang)
                                    .addComponent(kodebuku)
                                    .addComponent(jdlbuku))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtkodebuku, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(txtjdlbuku)
                                    .addComponent(txtpengarang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(penerbit)
                                        .addGap(46, 46, 46)
                                        .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thnterbit)
                                            .addComponent(hargabuku))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtharga)
                                            .addComponent(txtthnterbit, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                                .addGap(11, 11, 11))))
                    .addComponent(databuku, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(databuku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penerbit)
                            .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thnterbit)
                            .addComponent(txtthnterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargabuku)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kodebuku)
                            .addComponent(txtkodebuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdlbuku)
                            .addComponent(txtjdlbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pengarang)
                            .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bedit)
                    .addComponent(bhapus)
                    .addComponent(bkeluar)
                    .addComponent(btambah))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtjdlbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjdlbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjdlbukuActionPerformed

    private void txtpengarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpengarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpengarangActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjdlbuku.getText();
        String pengarang = txtpengarang.getText();
        String thntebit = txtthnterbit.getText();
        String penerbit = txtpenerbit.getText();
        String harga = txtharga.getText();
        try {
            st = koneksi.createStatement();
            st.executeUpdate("insert into buku VALUES ('"+ kodebuku +"','"
                    + judulbuku +"','"
                    + pengarang +"','"
                    + thntebit +"','"
                    + penerbit +"','"
                    + harga +"');");
            Tampilbuku();
            JOptionPane.showMessageDialog(null, "Tersimpan");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan\n"+e.getMessage());
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjdlbuku.getText();
        String pengarang = txtpengarang.getText();
        String thntebit = txtthnterbit.getText();
        String penerbit = txtpenerbit.getText();
        String harga = txtharga.getText();
        try {
            st = koneksi.createStatement();
                st.executeUpdate("update buku SET kodeBuku='"+kodebuku+"',"
                        +"judulBuku='"+judulbuku+"',"
                        +"pengarang='"+pengarang+"',"
                        +"penerbit='"+penerbit+"',"
                        +"tahunTerbit='"+thntebit+"',"
                        +"hargabuku='"+harga+"'" 
                        + "WHERE kodeBuku='"+kodebuku+"' OR judulBuku='"+judulbuku+"'");
            Tampilbuku();
            JOptionPane.showMessageDialog(null, "Teredit");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Teredit\n"+e.getMessage());
        }
    }//GEN-LAST:event_beditActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String kodebuku = txtkodebuku.getText();
        String judulbuku = txtjdlbuku.getText();
        String pengarang = txtpengarang.getText();
        String thntebit = txtthnterbit.getText();
        String penerbit = txtpenerbit.getText();
        String harga = txtharga.getText();
        try {
            st = koneksi.createStatement();
            st.executeUpdate("delete from buku where kodeBuku='"+kodebuku+"' OR judulBuku='"+judulbuku+"';");
            Tampilbuku();
            JOptionPane.showMessageDialog(null, "Terhapus");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Terhapus\n"+e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        new menuutama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txtkodebukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodebukuKeyPressed
        
    }//GEN-LAST:event_txtkodebukuKeyPressed

    private void txtkodebukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodebukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodebukuActionPerformed

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        txtkodebuku.setText("");
        txtjdlbuku.setText("");
        txtpengarang.setText("");
        txtpenerbit.setText("");
        txtthnterbit.setText("");
        txtharga.setText("");
        txtkodebuku.requestFocus();
    }//GEN-LAST:event_btambahActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        int a = tabel1.getSelectedRow();
        if (a == -1){
            return;
        }
        String kodeBuku = (String) tabel1.getValueAt(a, 0);
        txtkodebuku.setText(kodeBuku);
        String judulBuku = (String) tabel1.getValueAt(a, 1);
        txtjdlbuku.setText(judulBuku);
        String pengarang = (String) tabel1.getValueAt(a, 2);
        txtpengarang.setText(pengarang);
        String penerbit = (String) tabel1.getValueAt(a, 3);
        txtpenerbit.setText(penerbit);
        String tahunTerbit = (String) tabel1.getValueAt(a, 4);
        txtthnterbit.setText(tahunTerbit);
        String hargaBuku = (String) tabel1.getValueAt(a, 5);
        txtharga.setText(hargaBuku);
    }//GEN-LAST:event_tabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bedit;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel databuku;
    private javax.swing.JLabel hargabuku;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jdlbuku;
    private javax.swing.JLabel kodebuku;
    private javax.swing.JLabel penerbit;
    private javax.swing.JLabel pengarang;
    private javax.swing.JTable tabel1;
    private javax.swing.JLabel thnterbit;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjdlbuku;
    private javax.swing.JTextField txtkodebuku;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txtthnterbit;
    // End of variables declaration//GEN-END:variables
}
