import javax.swing.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import koneksi.koneksi;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class pengembalian extends javax.swing.JFrame {
    Statement st;
    Connection koneksi;
    ResultSet Res;
    String tanggal, tanggal1;
    
    public pengembalian() {
        initComponents();
        koneksi();
        tampilkan();
        pilihpinjam();
    }
    
    private void koneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi=DriverManager.getConnection("jdbc:mysql://localhost:3306/perpustakaan","root","");
            JOptionPane.showMessageDialog(null, "Koneksi Berhasil");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi Gagal");
        }
    }
    
    private void tampilkan() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. Pengembalian");
        model.addColumn("Stambuk");
        model.addColumn("Tanggal Peminjaman");
        model.addColumn("Tanggal Pengembalian");
        model.addColumn("No. Peminjaman");
        model.addColumn("Lama Pinjam");
        model.addColumn("Denda");
        
        tabelkembali.setModel(model);
        try {
            st = koneksi.createStatement();
            Res = st.executeQuery("select * from pengembalian");
            while (Res.next()) {
                model.addRow(new Object[]{
                    Res.getString("noPengembalian"),
                    Res.getString("stambuk"),
                    Res.getDate("tanggalPinjam"),
                    Res.getDate("tanggalKembali"),
                    Res.getString("noPeminjaman"),
                    Res.getInt("keterlambatan"),
                    Res.getInt("denda"),
                });
                tabelkembali.setModel(model);
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }
    
    private void pilihpinjam() {
        cbtnopin.removeAllItems();
        cbtnopin.addItem("Select");
        try {
            String sql = "select * from peminjaman";
            st = koneksi.createStatement();
            Res = st.executeQuery(sql);
            while (Res.next()) {
                String nopin = Res.getString("noPeminjaman");
                cbtnopin.addItem(nopin);
            }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkembali = new javax.swing.JTable();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        txtnokem = new javax.swing.JTextField();
        cbtnopin = new javax.swing.JComboBox<>();
        jkembali = new com.toedter.calendar.JDateChooser();
        txtlambat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jmldenda = new javax.swing.JLabel();
        txtjmlpinjam = new javax.swing.JTextField();
        txtstambuk = new javax.swing.JTextField();
        bhitungdenda = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        blambat = new javax.swing.JButton();
        jpinjam = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PENGEMBALIAN");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("NO PENGEMBALIAN");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("NO PEMINJAMAN");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("STAMBUK");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("TANGGAL PINJAM");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("TOTAL PINJAM");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("TANGGAL KEMBALI");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("LAMA PINJAM");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("DENDA");

        tabelkembali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkembaliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelkembali);

        bsimpan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bhapus.setText("HAPUS");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        bbatal.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bbatal.setText("BATAL");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bkeluar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bkeluar.setText("KELUAR");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        txtnokem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cbtnopin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbtnopin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbtnopin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnopinActionPerformed(evt);
            }
        });

        jkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jkembaliPropertyChange(evt);
            }
        });

        txtlambat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel10.setText("Catatan");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel11.setText("Jika Pemngembalian > 1 Minggu");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jLabel12.setText("Denda 1.000 / Buku");

        jLabel13.setText("( 5 hari )");

        jmldenda.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jmldenda.setText("0,-");

        txtjmlpinjam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtstambuk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bhitungdenda.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        bhitungdenda.setText("Hitung Denda");
        bhitungdenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungdendaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setText("Hari");

        blambat.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        blambat.setText("Proses");
        blambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blambatActionPerformed(evt);
            }
        });

        jpinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jpinjamPropertyChange(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("KEHILANGAN BUKU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnokem, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbtnopin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtjmlpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtstambuk)
                                    .addComponent(jpinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtlambat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel15)
                                                .addGap(18, 18, 18)
                                                .addComponent(blambat))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jmldenda, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel9))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel11))
                                        .addComponent(bhitungdenda))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addGap(4, 4, 4)))
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(362, 395, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bbatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bkeluar)
                        .addGap(52, 52, 52))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7)
                        .addComponent(txtnokem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blambat, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtlambat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbtnopin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtstambuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jmldenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bhitungdenda)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjmlpinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bhapus)
                    .addComponent(bbatal)
                    .addComponent(bkeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jkembaliPropertyChange
        if (jkembali.getDate() !=null) {
            SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
            tanggal1 = String.valueOf(format.format(jkembali.getDate()));
            }
    }//GEN-LAST:event_jkembaliPropertyChange

    private void cbtnopinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnopinActionPerformed
        try {
            String sql = "select * from peminjaman where noPeminjaman='"+cbtnopin.getSelectedItem()+"'";
            st = koneksi.createStatement();
            Res = st.executeQuery(sql);
            while (Res.next()) {
                txtstambuk.setText(Res.getString("stambuk"));
                jpinjam.setDate(Res.getDate("tanggalPinjam"));
                txtjmlpinjam.setText(Res.getString("totalPinjam"));    
            }
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_cbtnopinActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        String nokem = txtnokem.getText();
        SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
            tanggal = String.valueOf(format.format(jpinjam.getDate()));
            tanggal1 = String.valueOf(format.format(jkembali.getDate()));
        String nopin = cbtnopin.getItemAt(cbtnopin.getSelectedIndex()).toString();
        String stambuk = txtstambuk.getText();
        String lambat = txtlambat.getText();
        String denda = jmldenda.getText();

        try {
            st = koneksi.createStatement();
            st.executeUpdate("insert into pengembalian VALUES ('"+ nokem +"','"
                    + stambuk +"','"
                    + tanggal +"','"
                    + tanggal1 +"','"
                    + nopin +"','"
                    + lambat +"','"
                    + denda +"');");
            tampilkan();
            JOptionPane.showMessageDialog(null, "Data Behasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e.getMessage());
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        String nokem = txtnokem.getText();
        SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
            tanggal = String.valueOf(format.format(jpinjam.getDate()));
            tanggal1 = String.valueOf(format.format(jkembali.getDate()));
        String nopin = cbtnopin.getItemAt(cbtnopin.getSelectedIndex()).toString();
        String stambuk = txtstambuk.getText();
        String lambat = txtlambat.getText();
        String tot = txtjmlpinjam.getText();
        String denda = jmldenda.getText();
        try {
            st = koneksi.createStatement();
            st.executeUpdate("delete from pengembalian where noPengembalian='"+nokem+"' OR noPeminjaman='"+nopin+"';");
            tampilkan();
            JOptionPane.showMessageDialog(null, "Terhapus");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Tidak Terhapus\n"+e.getMessage());
        }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        cbtnopin.setSelectedItem("Select");
        txtnokem.setText("");
        txtstambuk.setText("");
        jpinjam.setDate(null);
        jkembali.setDate(null);
        txtlambat.setText("");
        txtjmlpinjam.setText("");
        txtnokem.requestFocus();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Apakah anda ingin Keluar?","Yakin",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bhitungdendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungdendaActionPerformed
        try {
            String nopin = (String) cbtnopin.getSelectedItem();
            Date tglpinjam = jpinjam.getDate();
            Date tglkembali = jkembali.getDate();
            long beda = Math.abs(tglkembali.getTime() - tglpinjam.getTime());
            int totaldenda =0;
            int jmlbuku;
            jmlbuku = Integer.parseInt(txtjmlpinjam.getText());
            
            if (TimeUnit.MILLISECONDS.toDays(beda) >=5) {
                int denda = (int) (TimeUnit.MILLISECONDS.toDays(beda));
                totaldenda=(1000*jmlbuku);
                jmldenda.setText(+totaldenda+"");
            }
            else {
                jmldenda.setText(""+0);
            }
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error "+e);
        }
    }//GEN-LAST:event_bhitungdendaActionPerformed

    private void jpinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jpinjamPropertyChange
        if (jpinjam.getDate() !=null) {
            SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
            tanggal = String.valueOf(format.format(jpinjam.getDate()));
            }
    }//GEN-LAST:event_jpinjamPropertyChange

    private void tabelkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkembaliMouseClicked
        int a = tabelkembali.getSelectedRow();
        if (a == -1){
            return;
        }
        String nokem = tabelkembali.getValueAt(a, 0).toString();
        txtnokem.setText(nokem);
        
        String nopin = tabelkembali.getValueAt(a, 1).toString();
        cbtnopin.setSelectedItem(nopin); 
        
        String kembali = tabelkembali.getValueAt(a, 3).toString();
        try {
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date d=f.parse(kembali);
            jkembali.setDate(d);
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_tabelkembaliMouseClicked

    private void blambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blambatActionPerformed
        try {
            DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggalpinjam = format.parse(tanggal);
            Date tanggalkembali = format.parse(tanggal1);
            long tanggalpinjam1 = tanggalpinjam.getTime();
            long tanggalkembali1 = tanggalkembali.getTime();
            long diff = tanggalkembali1 - tanggalpinjam1;
            long lama = diff / (24 * 60 * 60 * 1000);
            txtlambat.setText(Long.toString(lama) + "");
        } catch (Exception e) {
            System.out.println("" + e.getMessage());
        }
    }//GEN-LAST:event_blambatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new kehilanganbuku().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bhitungdenda;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blambat;
    private javax.swing.JButton bsimpan;
    private javax.swing.JComboBox<String> cbtnopin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jkembali;
    private javax.swing.JLabel jmldenda;
    private com.toedter.calendar.JDateChooser jpinjam;
    private javax.swing.JTable tabelkembali;
    private javax.swing.JTextField txtjmlpinjam;
    private javax.swing.JTextField txtlambat;
    private javax.swing.JTextField txtnokem;
    private javax.swing.JTextField txtstambuk;
    // End of variables declaration//GEN-END:variables
}
